apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    env: develop
    app: test-project-2-service
  name: test-project-2-service
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: test-project-2-pod
status:
  loadBalancer: {}